# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'WatchKitDemo' do

pod 'ApiAIWatchKit/WatchKitForPhone', :path => '../'

end

target 'WatchKitDemoTests' do

end

target 'WatchKitDemo WatchKit Extension' do

pod 'ApiAIWatchKit/WatchKitForWatch', :path => '../'

end

target 'WatchKitDemo WatchKit App' do

end

